<a href="https://colab.research.google.com/github/Jyothi-rao/23CSBTB39-40/blob/main/jyothi_nadipelli.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
list1={"chinni","robot",5}
print(list1)
array1=np.array([5,6,7,8,9])
print(array1)
array2=np.array([1,2,3,4,5])
print(array2)
n=array1+array2
print(n)
f=array1*array2
print(f)
g=array1**array2
print(g)
h=array1/array2
print(h)

{'chinni', 5, 'robot'}
[5 6 7 8 9]
[1 2 3 4 5]
[ 6  8 10 12 14]
[ 5 12 21 32 45]
[    5    36   343  4096 59049]
[5.         3.         2.33333333 2.         1.8       ]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')